// Static metadata for all Dominion expansions
// dataKey must match the expansion name in dominion_data.json cards
// Box art images stored locally in public/images/expansions/

const EXPANSIONS = [
  {
    name: 'Dominion',
    dataKey: 'Base',
    year: 2008,
    bggUrl: 'https://boardgamegeek.com/boardgame/36218/dominion',
    coverImg: '/images/expansions/base.jpg',
    keyMechanics: [
      'Stokksmíði (fann upp tegundina)',
      'Aðgerðar-, fjársjóðs- og sigurspil',
      'Ríkisspil í framboðsstöflum',
      'Rusla spilum í ruslatunnuna',
    ],
    funFacts: [
      'Vann Spiel des Jahres verðlaunin árið 2009 og er almennt talið hafa fundið upp stokksmíðitegundina.',
      'Donald X. Vaccarino byrjaði að hanna Dominion árið 2006 — upphaflega sem spil þar sem leikmenn skiptu um reglurnar.',
      'Í fyrstu útgáfunni voru 25 ólík ríkisspil — nú eru yfir 400 í allri seríunni.',
    ],
    has2ndEdition: true,
    secondEditionYear: 2016,
  },
  {
    name: 'Intrigue',
    dataKey: 'Intrigue',
    year: 2009,
    bggUrl: 'https://boardgamegeek.com/boardgame/40834/dominion-intrigue',
    coverImg: '/images/expansions/intrigue.jpg',
    keyMechanics: [
      'Valspil (veldu eitt af mörgum áhrifum)',
      'Sigurspil með sérstökum hæfileikum',
      'Meiri samskipti milli leikmanna',
    ],
    funFacts: [
      'Var upphaflega sjálfstætt spil; 2. útgáfan gerði það að viðbót og skipti út 7 ríkisspilum.',
      'Inniheldur flest valspil allra viðbóta — þú þarft alltaf að taka erfiðar ákvarðanir.',
      'Torturer er eitt mest hatuðu Dominion-spilin — kúga andstæðinga með handavali.',
    ],
    has2ndEdition: true,
    secondEditionYear: 2016,
  },
  {
    name: 'Seaside',
    dataKey: 'Seaside',
    year: 2009,
    bggUrl: 'https://boardgamegeek.com/boardgame/51811/dominion-seaside',
    coverImg: '/images/expansions/seaside.jpg',
    keyMechanics: [
      'Duration-spil (áhrif sem ná yfir margar umferðir)',
      'Spilamattar (Native Village, Pirate Ship)',
      'Leggja spil til hliðar',
    ],
    funFacts: [
      'Kynnti Duration-spil (appelsínugulur rammi) sem eru ein vinsælasta mekaníkin í allri seríunni.',
      'Wharf er oft nefnt sem eitt öflugasta spilið í Dominion — tveir auka spil og tvö auka kaup, í tvo hringi.',
      'Sjóræningjaþemað gerir þetta að einni skemmtilegustu viðbótanna fyrir nýja leikmenn.',
    ],
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Alchemy',
    dataKey: 'Alchemy',
    year: 2010,
    bggUrl: 'https://boardgamegeek.com/boardgame/66098/dominion-alchemy',
    coverImg: '/images/expansions/alchemy.jpg',
    portraitImg: true,
    isSmallBox: true,
    keyMechanics: [
      'Seyðakostnaður (ný gjaldmiðilstegund)',
      'Seyði-fjársjóðsspil',
      'Öflugar aðgerðakeðjur',
    ],
    funFacts: [
      'Umdeildasta viðbótin -- lítill kassi sem klauf samfélagið um hvort seyðakostnaður væri snilld eða pirrandi.',
      'Possession er bannað í flestum keppnisreglum vegna þess hversu leiðinlegt og pirrandi það getur verið.',
      'Aðeins 12 ríkisspil — minnsta viðbótin í Dominion seríunni.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Prosperity',
    dataKey: 'Prosperity',
    year: 2010,
    bggUrl: 'https://boardgamegeek.com/boardgame/66690/dominion-prosperity',
    coverImg: '/images/expansions/prosperity.jpg',
    keyMechanics: [
      'Platinum og Colony (verðmætari fjársjóður og sigurspil)',
      'Sigurstigatákn (VP tokens)',
      'Dýr ríkisspil (kostnaður 6+)',
      'Fjársjóðsspil með sérstökum hæfileikum',
    ],
    funFacts: [
      'Oft talin besta fyrsta viðbótin til kaupa, með Platinum og Colony fyrir ríkari upplifun.',
      'King\'s Court er þrefaldur Throne Room — eitt öflugasta spilið sem til er.',
      'Platinum (5 myntar) og Colony (10 stig) breyta öllu um hraða og stefnu leikja.',
    ],
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Cornucopia',
    dataKey: 'Cornucopia & Guilds',
    year: 2011,
    bggUrl: 'https://boardgamegeek.com/boardgame/90850/dominion-cornucopia',
    coverImg: '/images/expansions/cornucopia.jpg',
    portraitImg: true,
    keyMechanics: [
      'Fjölbreytni verðlaunuð (hagur af fjölbreyttum stokkum)',
      'Verðlaunaspil (einstök spil í gegnum Tournament)',
    ],
    funFacts: [
      'Smákassaviðbót sem verðlaunaði fjölbreytni í stokknum. Sameinuð Guilds í einn kassa árið 2023.',
      'Tournament → Province keðjan er ein dramatískasta stundin í Dominion — allir bíða spenntir.',
      'Fairgrounds getur gefið allt að 8 stig ef stokkurinn þinn er nógu fjölbreyttur.',
    ],
    has2ndEdition: false,
    mergedInto: 'Cornucopia & Guilds',
  },
  {
    name: 'Guilds',
    dataKey: 'Cornucopia & Guilds',
    year: 2013,
    bggUrl: 'https://boardgamegeek.com/boardgame/137166/dominion-guilds',
    coverImg: '/images/expansions/guilds.jpg',
    portraitImg: true,
    keyMechanics: [
      'Coffers-tákn (geyma mynt milli umferða)',
      'Ofborgun (borga meira fyrir bónusáhrif)',
    ],
    funFacts: [
      'Smákassaviðbót sem kynnti Coffers-tákn. Sameinuð Cornucopia í einn kassa árið 2023.',
      'Baker gefur öllum eitt Coffers-tákn í byrjun — eini kortið sem breytir upphafsstöðu leiksins.',
      'Ofborgunarmekaníkin bætti nýju dýpt við kaupákvarðanir — borga meira núna eða spara til síðar?',
    ],
    has2ndEdition: false,
    mergedInto: 'Cornucopia & Guilds',
  },
  {
    name: 'Hinterlands',
    dataKey: 'Hinterlands',
    year: 2011,
    bggUrl: 'https://boardgamegeek.com/boardgame/104557/dominion-hinterlands',
    coverImg: '/images/expansions/hinterlands.jpg',
    keyMechanics: [
      'Áhrif við öflun (spil virkjast þegar þau fást)',
      'Áhrif við kaup',
      'Viðbragðsspil (Reaction)',
    ],
    funFacts: [
      'Snýst um spil sem gera eitthvað um leið og þú færð þau, sem gerir kaupfasann mun gagnvirkari.',
      'Haggler var svo vinsælt að „öflun-áhrif" mekaníkin var endurnotuð í mörgum síðari viðbótum.',
      'Border Village gefur þér ókeypis spil þegar þú kaupir það — eitt besta verðmætið í leiknum.',
    ],
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Dark Ages',
    dataKey: 'Dark Ages',
    year: 2012,
    bggUrl: 'https://boardgamegeek.com/boardgame/125403/dominion-dark-ages',
    coverImg: '/images/expansions/dark_ages.jpg',
    keyMechanics: [
      'Shelters (koma í stað upphaflegra Estate-spila)',
      'Ruins (ruslspil sem andstæðingar fá)',
      'Spil sem nýta ruslatunnuna',
      'Knights (einstök árásarbunki)',
      'Uppfærsla og umbreyting spila',
    ],
    funFacts: [
      'Stærsta viðbótin með 500 spilum, með ruslatunnuþema og einstöku Knights-árásarbunkunni.',
      'Knights eru 10 ólík spil í einum bunka — eina handahófsárásin í leiknum.',
      'Shelters breyta byrjun leiksins — engin Estate-spil, þess í stað þrjú einstök 1-myntar spil.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Adventures',
    dataKey: 'Adventures',
    year: 2015,
    bggUrl: 'https://boardgamegeek.com/boardgame/171915/dominion-adventures',
    coverImg: '/images/expansions/adventures.jpg',
    keyMechanics: [
      'Reserve-spil (lögð til hliðar á Tavern-matta, kölluð síðar)',
      'Events (kaupa áhrif í stað spils)',
      'Tákn á bunka (+Spil, +Aðgerð, +Kaup, +Mynt)',
      'Traveller-uppfærslulínur',
    ],
    funFacts: [
      'Kynnti Events -- kaupanleg áhrif sem eru ekki spil -- sem stækkuðu möguleikana í kaupfasanum.',
      'Page → Champion uppfærslulínan er ein sú lengsta og verðmætasta í Dominion.',
      'Lost Arts setur +Aðgerð tákn á bunka — gerir hvaða spil sem er að „Village".',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Empires',
    dataKey: 'Empires',
    year: 2016,
    bggUrl: 'https://boardgamegeek.com/boardgame/192951/dominion-empires',
    coverImg: '/images/expansions/empires.jpg',
    keyMechanics: [
      'Skuldatákn (kaupa núna, borga síðar)',
      'Landmarks (ný lokastigagjöf)',
      'Klofnir bunkar (tvö ólík spil í einum bunka)',
      'Sigurstigatákn aukin',
    ],
    funFacts: [
      'Skuldatákn leyfa þér að eignast dýr spil strax en þú verður að borga skuldina áður en þú kaupir aftur.',
      'Landmarks breyta stigagjöfinni á ófyrirsjáanlegan hátt — geta snúið leiknum algjörlega á haus.',
      'Donate Event leyfir þér að rusla öllu úr stokknum þínum í einu — róttæk aðgerð.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Nocturne',
    dataKey: 'Nocturne',
    year: 2017,
    bggUrl: 'https://boardgamegeek.com/boardgame/232452/dominion-nocturne',
    coverImg: '/images/expansions/nocturne.jpg',
    keyMechanics: [
      'Næturhluti (nýr fasi eftir kaup)',
      'Heirlooms (koma í stað upphaflegra Copper-spila)',
      'Boons og Hexes (handahófskenndar blessanir og bölvanir)',
      'States (varanleg ástand leikmanna)',
      'Anda- og draugaspil',
    ],
    funFacts: [
      'Bætti við alveg nýjum næturhluta og skipti upphaflegum Copper-spilum út fyrir einstök Heirloom-fjársjóðsspil.',
      'Vampire/Bat er eina spilið sem breytist fram og til baka milli tveggja spila.',
      'Draugaspilin (Ghosts) eru Duration-spil sem þú getur aldrei keypt beint — þau koma alltaf úr öðrum spilum.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Renaissance',
    dataKey: 'Renaissance',
    year: 2018,
    bggUrl: 'https://boardgamegeek.com/boardgame/257673/dominion-renaissance',
    coverImg: '/images/expansions/renaissance.jpg',
    keyMechanics: [
      'Villagers (geyma +Aðgerðir fyrir síðari umferðir)',
      'Coffers formlega kynnt',
      'Projects (varanlegir hæfileikar keyptir einu sinni)',
      'Artifacts (einstakir hlutir sem leikmenn keppast um)',
    ],
    funFacts: [
      'Projects eru varanleg uppfærsla sem keypt er einu sinni -- eins og að velja óvirkan hæfileika sem mótar alla stefnu leiksins.',
      'Villagers leyfa þér að geyma +Aðgerðir — engin afsökun lengur fyrir „ég gat ekki spilað öllu mínu".',
      'Cathedral er Project sem ruslar einu spili sjálfkrafa í hverri umferð — öflugt en hættulegt.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Menagerie',
    dataKey: 'Menagerie',
    year: 2020,
    bggUrl: 'https://boardgamegeek.com/boardgame/298055/dominion-menagerie',
    coverImg: '/images/expansions/menagerie.jpg',
    keyMechanics: [
      'Horses (einnota cantrip sem skilar sér í bunka)',
      'Exile-matti (leggja spil til hliðar, fá aftur síðar)',
      'Ways (gefa hvaða aðgerðarspili sem er aðra getu)',
    ],
    funFacts: [
      'Ways leyfa þér að nota hvaða aðgerðarspil sem er eins og það væri annað spil -- ómældir samsetningarmöguleikar.',
      'Horses eru einnota „cantrips" — spilaðu þau og þau hverfa, en þau koma aftur í framboðsstöfluna.',
      'Kom út á COVID tímanum og var afar vinsæl á netinu á dominion.games.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Allies',
    dataKey: 'Allies',
    year: 2022,
    bggUrl: 'https://boardgamegeek.com/boardgame/347307/dominion-allies',
    coverImg: '/images/expansions/allies.jpg',
    keyMechanics: [
      'Ally-spil (sameiginlegir viðvarandi hæfileikar)',
      'Favor-tákn (nýr gjaldmiðill fyrir Ally-hæfileika)',
      'Snúnings-klofinbunkar',
      'Liaisons (spil sem tengjast Ally-spilinu)',
    ],
    funFacts: [
      'Í hverjum leik er eitt handahófskennt Ally-spil sem allir leikmenn deila og breytir öllu um stefnumótun.',
      'Snúnings-klofinbunkar hafa tvö spil sem skiptast á — þú veist ekki alltaf hvort þú færð.',
      'Ally-mekaníkin tryggir að engir tveir leikir séu eins, jafnvel með sömu ríkisspilum.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Plunder',
    dataKey: 'Plunder',
    year: 2022,
    bggUrl: 'https://boardgamegeek.com/boardgame/369536/dominion-plunder',
    coverImg: '/images/expansions/plunder.jpg',
    keyMechanics: [
      'Loot (handahófskennd hágæða fjársjóðsspil)',
      'Traits (breytingar á ríkisspilabunkum)',
      'Duration-spil koma aftur af krafti',
      'Fjársjóðsspil með öflugum áhrifum',
    ],
    funFacts: [
      'Loot-spil eru handahófskennd einstök fjársjóðsspil -- þú veist aldrei hvaða fjársjóð þú færð.',
      'Traits breyta eiginleikum ríkisspilabunka — sama spilið getur verið ólíkt frá leik til leiks.',
      'Stærsta viðbótin frá Dark Ages — rúmlega 500 spil í kassanum.',
    ],
    has2ndEdition: false,
  },
  {
    name: 'Cornucopia & Guilds',
    dataKey: 'Cornucopia & Guilds',
    year: 2023,
    bggUrl: 'https://boardgamegeek.com/boardgame/382060/dominion-cornucopia-guilds',
    coverImg: '/images/expansions/cornucopia_guilds_2nd.jpg',
    keyMechanics: [
      'Fjölbreytni verðlaunuð (hagur af fjölbreyttum stokkum)',
      'Verðlaunaspil (einstök spil í gegnum Tournament)',
      'Coffers-tákn (geyma mynt milli umferða)',
      'Ofborgun (borga meira fyrir bónusáhrif)',
    ],
    funFacts: [
      'Sameinuð 2. útgáfa tveggja smákassaviðbóta (Cornucopia 2011 og Guilds 2013) í einn kassa með nýjum spilum.',
      'Bætti við 7 alveg nýjum spilum sem voru ekki í upprunalegu viðbótunum.',
      'Fyrsta „samruni" í Dominion sögunni — tvær viðbætur í einn kassa.',
    ],
    has2ndEdition: true,
    secondEditionYear: 2023,
    isMergedEdition: true,
  },
  {
    name: 'Rising Sun',
    dataKey: 'Rising Sun',
    year: 2024,
    bggUrl: 'https://boardgamegeek.com/boardgame/420298/dominion-rising-sun',
    coverImg: '/images/expansions/rising_sun.jpg',
    keyMechanics: [
      'Shadows (spil sem hægt er að spila utan venjulegra fasa)',
      'Prophecy (atburðir sem virkjast við tæmingu bunka)',
      'Skuldatákn koma aftur',
    ],
    funFacts: [
      'Fyrsta viðbótin með raunverulegu menningarþema (Japan), með Shadow-spilum sem hægt er að spila á óvenjulegum tímum.',
      'Prophecy-spil virkjast þegar bunkar tæmast — bætir spennu við lok leikja.',
      'Nýjasta viðbótin í seríunni og sú fyrsta eftir þriggja ára hlé.',
    ],
    has2ndEdition: false,
  },
]

export default EXPANSIONS
