// Static metadata for all Dominion expansions
// dataKey must match the expansion name in dominion_data.json cards
// Box art images stored locally in public/images/expansions/

const EXPANSIONS = [
  {
    name: 'Dominion',
    dataKey: 'Base',
    year: 2008,
    bggUrl: 'https://boardgamegeek.com/boardgame/36218/dominion',
    coverImg: '/images/expansions/base.jpg',
    keyMechanics: [
      'Stokksmíði (fann upp tegundina)',
      'Aðgerðar-, fjársjóðs- og sigurspil',
      'Ríkisspil í framboðsstöflum',
      'Rusla spilum í ruslatunnuna',
    ],
    funFact: 'Vann Spiel des Jahres verðlaunin árið 2009 og er almennt talið hafa fundið upp stokksmíðitegundina.',
    has2ndEdition: true,
    secondEditionYear: 2016,
  },
  {
    name: 'Intrigue',
    dataKey: 'Intrigue',
    year: 2009,
    bggUrl: 'https://boardgamegeek.com/boardgame/40834/dominion-intrigue',
    coverImg: '/images/expansions/intrigue.jpg',
    keyMechanics: [
      'Valspil (veldu eitt af mörgum áhrifum)',
      'Sigurspil með sérstökum hæfileikum',
      'Meiri samskipti milli leikmanna',
    ],
    funFact: 'Var upphaflega sjálfstætt spil; 2. útgáfan gerði það að viðbót og skipti út 7 ríkisspilum.',
    has2ndEdition: true,
    secondEditionYear: 2016,
  },
  {
    name: 'Seaside',
    dataKey: 'Seaside',
    year: 2009,
    bggUrl: 'https://boardgamegeek.com/boardgame/51811/dominion-seaside',
    coverImg: '/images/expansions/seaside.jpg',
    keyMechanics: [
      'Duration-spil (áhrif sem ná yfir margar umferðir)',
      'Spilamattar (Native Village, Pirate Ship)',
      'Leggja spil til hliðar',
    ],
    funFact: 'Kynnti Duration-spil (appelsínugulur rammi) sem eru ein vinsælasta mekaníkin í allri seríunni.',
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Alchemy',
    dataKey: 'Alchemy',
    year: 2010,
    bggUrl: 'https://boardgamegeek.com/boardgame/66098/dominion-alchemy',
    coverImg: '/images/expansions/alchemy.jpg',
    portraitImg: true,
    isSmallBox: true,
    keyMechanics: [
      'Seyðakostnaður (ný gjaldmiðilstegund)',
      'Potion-fjársjóðsspil',
      'Öflugar aðgerðakeðjur',
    ],
    funFact: 'Umdeildasta viðbótin -- lítill kassi sem klauf samfélagið um hvort seyðakostnaður væri snilld eða pirrandi.',
    has2ndEdition: false,
  },
  {
    name: 'Prosperity',
    dataKey: 'Prosperity',
    year: 2010,
    bggUrl: 'https://boardgamegeek.com/boardgame/66690/dominion-prosperity',
    coverImg: '/images/expansions/prosperity.jpg',
    keyMechanics: [
      'Platinum og Colony (verðmætari fjársjóður og sigurspil)',
      'Sigurstigatákn (VP tokens)',
      'Dýr ríkisspil (kostnaður 6+)',
      'Fjársjóðsspil með sérstökum hæfileikum',
    ],
    funFact: 'Oft talin besta fyrsta viðbótin til kaupa, með Platinum og Colony fyrir ríkari upplifun.',
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Cornucopia',
    dataKey: 'Cornucopia & Guilds',
    year: 2011,
    bggUrl: 'https://boardgamegeek.com/boardgame/90850/dominion-cornucopia',
    coverImg: '/images/expansions/cornucopia.jpg',
    portraitImg: true,
    keyMechanics: [
      'Fjölbreytni verðlaunuð (hagur af fjölbreyttum stokkum)',
      'Verðlaunaspil (einstök spil í gegnum Tournament)',
    ],
    funFact: 'Smákassaviðbót sem verðlaunaði fjölbreytni í stokknum. Sameinuð Guilds í einn kassa árið 2023.',
    has2ndEdition: false,
    mergedInto: 'Cornucopia & Guilds',
  },
  {
    name: 'Guilds',
    dataKey: 'Cornucopia & Guilds',
    year: 2013,
    bggUrl: 'https://boardgamegeek.com/boardgame/137166/dominion-guilds',
    coverImg: '/images/expansions/guilds.jpg',
    portraitImg: true,
    keyMechanics: [
      'Coffers-tákn (geyma mynt milli umferða)',
      'Ofborgun (borga meira fyrir bónusáhrif)',
    ],
    funFact: 'Smákassaviðbót sem kynnti Coffers-tákn. Sameinuð Cornucopia í einn kassa árið 2023.',
    has2ndEdition: false,
    mergedInto: 'Cornucopia & Guilds',
  },
  {
    name: 'Cornucopia & Guilds',
    dataKey: 'Cornucopia & Guilds',
    year: 2023,
    bggUrl: 'https://boardgamegeek.com/boardgame/382060/dominion-cornucopia-guilds',
    coverImg: '/images/expansions/cornucopia_guilds_2nd.jpg',
    keyMechanics: [
      'Fjölbreytni verðlaunuð (hagur af fjölbreyttum stokkum)',
      'Verðlaunaspil (einstök spil í gegnum Tournament)',
      'Coffers-tákn (geyma mynt milli umferða)',
      'Ofborgun (borga meira fyrir bónusáhrif)',
    ],
    funFact: 'Sameinuð 2. útgáfa tveggja smákassaviðbóta (Cornucopia 2011 og Guilds 2013) í einn kassa með nýjum spilum.',
    has2ndEdition: true,
    secondEditionYear: 2023,
    isMergedEdition: true,
  },
  {
    name: 'Hinterlands',
    dataKey: 'Hinterlands',
    year: 2011,
    bggUrl: 'https://boardgamegeek.com/boardgame/104557/dominion-hinterlands',
    coverImg: '/images/expansions/hinterlands.jpg',
    keyMechanics: [
      'Áhrif við öflun (spil virkjast þegar þau fást)',
      'Áhrif við kaup',
      'Viðbragðsspil (Reaction)',
    ],
    funFact: 'Snýst um spil sem gera eitthvað um leið og þú færð þau, sem gerir kaupfasann mun gagnvirkari.',
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Dark Ages',
    dataKey: 'Dark Ages',
    year: 2012,
    bggUrl: 'https://boardgamegeek.com/boardgame/125403/dominion-dark-ages',
    coverImg: '/images/expansions/dark_ages.jpg',
    keyMechanics: [
      'Shelters (koma í stað upphaflegra Estate-spila)',
      'Ruins (ruslspil sem andstæðingar fá)',
      'Spil sem nýta ruslatunnuna',
      'Knights (einstök árásarbunki)',
      'Uppfærsla og umbreyting spila',
    ],
    funFact: 'Stærsta viðbótin með 500 spilum, með ruslatunnuþema og einstöku Knights-árásarbunkunni.',
    has2ndEdition: false,
  },
  {
    name: 'Adventures',
    dataKey: 'Adventures',
    year: 2015,
    bggUrl: 'https://boardgamegeek.com/boardgame/171915/dominion-adventures',
    coverImg: '/images/expansions/adventures.jpg',
    keyMechanics: [
      'Reserve-spil (lögð til hliðar á Tavern-matta, kölluð síðar)',
      'Events (kaupa áhrif í stað spils)',
      'Tákn á bunka (+Spil, +Aðgerð, +Kaup, +Mynt)',
      'Traveller-uppfærslulínur',
    ],
    funFact: 'Kynnti Events -- kaupanleg áhrif sem eru ekki spil -- sem stækkuðu möguleikana í kaupfasanum.',
    has2ndEdition: false,
  },
  {
    name: 'Empires',
    dataKey: 'Empires',
    year: 2016,
    bggUrl: 'https://boardgamegeek.com/boardgame/192951/dominion-empires',
    coverImg: '/images/expansions/empires.jpg',
    keyMechanics: [
      'Skuldatákn (kaupa núna, borga síðar)',
      'Landmarks (ný lokastigagjöf)',
      'Klofnir bunkar (tvö ólík spil í einum bunka)',
      'Sigurstigatákn aukin',
    ],
    funFact: 'Skuldatákn leyfa þér að eignast dýr spil strax en þú verður að borga skuldina áður en þú kaupir aftur.',
    has2ndEdition: false,
  },
  {
    name: 'Nocturne',
    dataKey: 'Nocturne',
    year: 2017,
    bggUrl: 'https://boardgamegeek.com/boardgame/232452/dominion-nocturne',
    coverImg: '/images/expansions/nocturne.jpg',
    keyMechanics: [
      'Næturhluti (nýr fasi eftir kaup)',
      'Heirlooms (koma í stað upphaflegra Copper-spila)',
      'Boons og Hexes (handahófskenndar blessanir og bölvanir)',
      'States (varanleg ástand leikmanna)',
      'Anda- og draugaspil',
    ],
    funFact: 'Bætti við alveg nýjum næturhluta og skipti upphaflegum Copper-spilum út fyrir einstök Heirloom-fjársjóðsspil.',
    has2ndEdition: false,
  },
  {
    name: 'Renaissance',
    dataKey: 'Renaissance',
    year: 2018,
    bggUrl: 'https://boardgamegeek.com/boardgame/257673/dominion-renaissance',
    coverImg: '/images/expansions/renaissance.jpg',
    keyMechanics: [
      'Villagers (geyma +Aðgerðir fyrir síðari umferðir)',
      'Coffers formlega kynnt',
      'Projects (varanlegir hæfileikar keyptir einu sinni)',
      'Artifacts (einstakir hlutir sem leikmenn keppast um)',
    ],
    funFact: 'Projects eru varanleg uppfærsla sem keypt er einu sinni -- eins og að velja óvirkan hæfileika sem mótar alla stefnu leiksins.',
    has2ndEdition: false,
  },
  {
    name: 'Menagerie',
    dataKey: 'Menagerie',
    year: 2020,
    bggUrl: 'https://boardgamegeek.com/boardgame/298055/dominion-menagerie',
    coverImg: '/images/expansions/menagerie.jpg',
    keyMechanics: [
      'Horses (einnota cantrip sem skilar sér í bunka)',
      'Exile-matti (leggja spil til hliðar, fá aftur síðar)',
      'Ways (gefa hvaða aðgerðarspili sem er aðra getu)',
    ],
    funFact: 'Ways leyfa þér að nota hvaða aðgerðarspil sem er eins og það væri annað spil -- ómældir samsetningarmöguleikar.',
    has2ndEdition: false,
  },
  {
    name: 'Allies',
    dataKey: 'Allies',
    year: 2022,
    bggUrl: 'https://boardgamegeek.com/boardgame/347307/dominion-allies',
    coverImg: '/images/expansions/allies.jpg',
    keyMechanics: [
      'Ally-spil (sameiginlegir viðvarandi hæfileikar)',
      'Favor-tákn (nýr gjaldmiðill fyrir Ally-hæfileika)',
      'Snúnings-klofinbunkar',
      'Liaisons (spil sem tengjast Ally-spilinu)',
    ],
    funFact: 'Í hverjum leik er eitt handahófskennt Ally-spil sem allir leikmenn deila og breytir öllu um stefnumótun.',
    has2ndEdition: false,
  },
  {
    name: 'Plunder',
    dataKey: 'Plunder',
    year: 2022,
    bggUrl: 'https://boardgamegeek.com/boardgame/369536/dominion-plunder',
    coverImg: '/images/expansions/plunder.jpg',
    keyMechanics: [
      'Loot (handahófskennd hágæða fjársjóðsspil)',
      'Traits (breytingar á ríkisspilabunkum)',
      'Duration-spil koma aftur af krafti',
      'Fjársjóðsspil með öflugum áhrifum',
    ],
    funFact: 'Loot-spil eru handahófskennd einstök fjársjóðsspil -- þú veist aldrei hvaða fjársjóð þú færð.',
    has2ndEdition: false,
  },
  {
    name: 'Rising Sun',
    dataKey: 'Rising Sun',
    year: 2024,
    bggUrl: 'https://boardgamegeek.com/boardgame/420298/dominion-rising-sun',
    coverImg: '/images/expansions/rising_sun.jpg',
    keyMechanics: [
      'Shadows (spil sem hægt er að spila utan venjulegra fasa)',
      'Prophecy (atburðir sem virkjast við tæmingu bunka)',
      'Skuldatákn koma aftur',
    ],
    funFact: 'Fyrsta viðbótin með raunverulegu menningarþema (Japan), með Shadow-spilum sem hægt er að spila á óvenjulegum tímum.',
    has2ndEdition: false,
  },
]

export default EXPANSIONS
