// Static metadata for all Dominion expansions
// dataKey must match the expansion name in dominion_data.json cards

const EXPANSIONS = [
  {
    name: 'Dominion',
    dataKey: 'Base',
    year: 2008,
    bggUrl: 'https://boardgamegeek.com/boardgame/36218/dominion',
    keyMechanics: [
      'Deck-building (invented the genre)',
      'Action, Treasure, Victory card types',
      'Kingdom card supply piles',
      'Trash mechanic',
    ],
    funFact: 'Won the 2009 Spiel des Jahres and invented the deck-building genre.',
    has2ndEdition: true,
    secondEditionYear: 2016,
  },
  {
    name: 'Intrigue',
    dataKey: 'Intrigue',
    year: 2009,
    bggUrl: 'https://boardgamegeek.com/boardgame/40834/dominion-intrigue',
    keyMechanics: [
      'Choice cards (choose one of multiple effects)',
      'Victory cards with abilities',
      'More player interaction',
    ],
    funFact: 'Originally a standalone game; the 2nd Edition made it expansion-only and swapped out 7 kingdom cards.',
    has2ndEdition: true,
    secondEditionYear: 2016,
  },
  {
    name: 'Seaside',
    dataKey: 'Seaside',
    year: 2009,
    bggUrl: 'https://boardgamegeek.com/boardgame/51811/dominion-seaside',
    keyMechanics: [
      'Duration cards (effects spanning multiple turns)',
      'Player mats (Native Village, Pirate Ship)',
      'Set-aside mechanics',
    ],
    funFact: 'Introduced Duration cards (orange-bordered), one of the most beloved mechanics in the series.',
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Alchemy',
    dataKey: 'Alchemy',
    year: 2010,
    bggUrl: 'https://boardgamegeek.com/boardgame/66098/dominion-alchemy',
    keyMechanics: [
      'Potion cost (new currency type)',
      'Potion treasure card',
      'Powerful action chains',
    ],
    funFact: 'The most controversial expansion -- a small box that divided the community over whether Potion costs were brilliant or annoying.',
    has2ndEdition: false,
  },
  {
    name: 'Prosperity',
    dataKey: 'Prosperity',
    year: 2010,
    bggUrl: 'https://boardgamegeek.com/boardgame/66690/dominion-prosperity',
    keyMechanics: [
      'Platinum and Colony (higher-value treasure and victory)',
      'Victory Point tokens',
      'Expensive kingdom cards (cost 6+)',
      'Treasure cards with abilities',
    ],
    funFact: 'Often cited as the best first expansion to buy, adding Platinum/Colony for a richer big-money experience.',
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Cornucopia & Guilds',
    dataKey: 'Cornucopia & Guilds',
    year: 2011,
    bggUrl: 'https://boardgamegeek.com/boardgame/90850/dominion-cornucopia',
    keyMechanics: [
      'Variety rewards (benefit from diverse decks)',
      'Prize cards (unique cards via Tournament)',
      'Coffers tokens (save coins between turns)',
      'Overpay mechanic (spend extra for bonus effects)',
    ],
    funFact: 'Two small-box expansions (Cornucopia 2011, Guilds 2013) combined into one box for the 2nd Edition in 2023.',
    has2ndEdition: true,
    secondEditionYear: 2023,
  },
  {
    name: 'Hinterlands',
    dataKey: 'Hinterlands',
    year: 2011,
    bggUrl: 'https://boardgamegeek.com/boardgame/104557/dominion-hinterlands',
    keyMechanics: [
      'When-gain effects (cards trigger on acquisition)',
      'When-buy effects',
      'Reaction cards',
    ],
    funFact: 'Focused on cards that do something the moment you gain them, making the Buy phase far more interactive.',
    has2ndEdition: true,
    secondEditionYear: 2022,
  },
  {
    name: 'Dark Ages',
    dataKey: 'Dark Ages',
    year: 2012,
    bggUrl: 'https://boardgamegeek.com/boardgame/125403/dominion-dark-ages',
    keyMechanics: [
      'Shelters (replace starting Estates)',
      'Ruins (junk cards given to opponents)',
      'Trash-interaction cards',
      'Knights (unique Attack pile)',
      'Upgrading/transforming cards',
    ],
    funFact: 'The largest expansion at 500 cards, featuring a trash-focused theme and the unique Knights attack pile.',
    has2ndEdition: false,
  },
  {
    name: 'Adventures',
    dataKey: 'Adventures',
    year: 2015,
    bggUrl: 'https://boardgamegeek.com/boardgame/171915/dominion-adventures',
    keyMechanics: [
      'Reserve cards (set aside on Tavern mat, call later)',
      'Events (buy an effect instead of a card)',
      'Tokens on piles (+Card, +Action, +Buy, +Coin)',
      'Traveller upgrade lines',
    ],
    funFact: 'Introduced Events -- purchasable effects that aren\'t cards -- fundamentally expanding what you can do on your Buy phase.',
    has2ndEdition: false,
  },
  {
    name: 'Empires',
    dataKey: 'Empires',
    year: 2016,
    bggUrl: 'https://boardgamegeek.com/boardgame/192951/dominion-empires',
    keyMechanics: [
      'Debt tokens (buy now, pay later)',
      'Landmarks (new end-game scoring)',
      'Split piles (two different cards in one pile)',
      'VP tokens expanded',
    ],
    funFact: 'Debt tokens let you acquire expensive cards immediately but you must pay off the debt before buying again.',
    has2ndEdition: false,
  },
  {
    name: 'Nocturne',
    dataKey: 'Nocturne',
    year: 2017,
    bggUrl: 'https://boardgamegeek.com/boardgame/232452/dominion-nocturne',
    keyMechanics: [
      'Night phase (new phase after Buy)',
      'Heirlooms (replace starting Coppers)',
      'Boons and Hexes (random blessings/curses)',
      'States (persistent player conditions)',
      'Spirit and Zombie cards',
    ],
    funFact: 'Added an entirely new Night phase and replaced starting Coppers with unique Heirloom treasures.',
    has2ndEdition: false,
  },
  {
    name: 'Renaissance',
    dataKey: 'Renaissance',
    year: 2018,
    bggUrl: 'https://boardgamegeek.com/boardgame/257673/dominion-renaissance',
    keyMechanics: [
      'Villagers (bank +Actions for later turns)',
      'Coffers formalized',
      'Projects (permanent one-time-buy abilities)',
      'Artifacts (unique items players compete for)',
    ],
    funFact: 'Projects are permanent upgrades you buy once -- like choosing a passive ability that shapes your entire strategy.',
    has2ndEdition: false,
  },
  {
    name: 'Menagerie',
    dataKey: 'Menagerie',
    year: 2020,
    bggUrl: 'https://boardgamegeek.com/boardgame/298055/dominion-menagerie',
    keyMechanics: [
      'Horses (one-use cantrip gained and returned)',
      'Exile mat (set aside cards, reclaim later)',
      'Ways (give any Action an alternate ability)',
    ],
    funFact: 'Ways let you use any Action card as if it were a different card, creating wild combinatorial possibilities.',
    has2ndEdition: false,
  },
  {
    name: 'Allies',
    dataKey: 'Allies',
    year: 2022,
    bggUrl: 'https://boardgamegeek.com/boardgame/347307/dominion-allies',
    keyMechanics: [
      'Ally cards (shared ongoing abilities)',
      'Favor tokens (new currency for Ally abilities)',
      'Rotating split piles',
      'Liaisons (cards that interact with your Ally)',
    ],
    funFact: 'Each game features one random Ally that all players share, fundamentally altering the strategy landscape every game.',
    has2ndEdition: false,
  },
  {
    name: 'Plunder',
    dataKey: 'Plunder',
    year: 2022,
    bggUrl: 'https://boardgamegeek.com/boardgame/369536/dominion-plunder',
    keyMechanics: [
      'Loot (randomized premium treasure cards)',
      'Traits (modifiers applied to kingdom piles)',
      'Duration cards return in force',
      'Treasures with powerful effects',
    ],
    funFact: 'Loot cards are randomized unique treasures -- you never know which premium treasure you\'ll get.',
    has2ndEdition: false,
  },
  {
    name: 'Rising Sun',
    dataKey: 'Rising Sun',
    year: 2024,
    bggUrl: 'https://boardgamegeek.com/boardgame/420298/dominion-rising-sun',
    keyMechanics: [
      'Shadows (cards playable outside normal phases)',
      'Prophecy (events triggered by pile depletion)',
      'Debt tokens return',
    ],
    funFact: 'The first expansion with a real-world cultural theme (Japan), featuring Shadow cards playable at unusual times.',
    has2ndEdition: false,
  },
]

export default EXPANSIONS
